### ISSUE TITLE
Does not build on latest SBCL - defconstant of cl:error

### ISSUE THREAD

**Issue by quicklisp** [McParen/croatoan#1]
I get this:

    Unhandled SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1002F276A3}>: Lock on package COMMON-LISP violated when defining ERROR as a constant while in package DE.ANVI.NCURSES.

http://report.quicklisp.org/2015-07-29/failure-report/croatoan.html#croatoan has a longer log.

**Comment by McParen** [comment]
Fixed a few days ago in [4cbcbfa](https://github.com/McParen/croatoan/commit/4cbcbfa0127972a64b9b91355209803d051ddac3).

Thanks for the notice.
