### ISSUE TITLE
Rate limiting key presses?

### ISSUE THREAD

**Issue by veddox** [McParen/croatoan#11]
Hey there :-)

Working on an adventure game, I noticed that when I hold down an arrow key for any length of time, the player character will continue travelling for quite some distance after I let go of the key. It seems to me that the act of holding down the key emits key events at a high frequency, and that these are stored in some sort of a stream until they can be processed by the program. Of course, this kind of "inertia" is no good for a game, and I would like to get rid of it. Is there currently a way to limit the maximum frequency at which key events are generated?

**Comment by McParen** [comment]
Hello veddox,

the behavior you observe is a limitation of the terminal. Ncurses or terminals in general do not have a "key release" event, so you cant detect when the character should stop. As far as I know, you also can not set the key repeat rate from ncurses, this is a x window system property (see "xset r rate").

What you could do is use the blocking timeout to set a frame rate for the unwanted events, and use the ncurses function flushinp to flush any characters remaining on the input buffer after you successfully handled the event.

**Comment by veddox** [comment]
> What you could do is use the blocking timeout to set a frame rate for the unwanted events [...] and use the ncurses function flushinp to flush any characters remaining on the input buffer after you successfully handled the event.

That sounds like a good workaround. Thank you!
