### ISSUE TITLE
Keypresses dropped when using remote swank connection

### ISSUE THREAD

**Issue by mjgordon** [McParen/croatoan#12]
Noticed this in my own program, confirmed with the (test1) example; about 1 in 5 keypresses don't get noticed by croatoan. This occurred while testing both the (event-case) loop and just (get-event). In all cases input-blocking is t. 

Further testing revealed this only occurs when connecting from slime. Running straight from command-line sbcl behaves normally. 

SBCL 1.4.5 Ubuntu 18.04

**Comment by McParen** [comment]
Hello mjgordon,

when connecting using slime/swank you have to consider that the slime repl is running in a different thread than the xterm repl and that all the standard lisp and ncurses have to be considered and properly redirected. Slime and swank do not perform this stream binding and redirection automatically.

I am personally not using slime at all when working with ncurses, so I cant help you there. Working out and writing down how to cleanly marry slime and ncurses so other people can use it is on my long-term todo list though.

**Comment by mjgordon** [comment]
I think it may actually be a general ncurses issue; I've now tested and gotten very similar results with cl-charms.

**Comment by McParen** [comment]
It is not a ncurses issue per se, the losses occur when calls to ncurses are made from slime's "repl-thread". When calls to ncurses are made from SBCL's main thread, the keys dont get lost. A working solution is to pass lambdas as "jobs" through a thread-safe queue from the slime thread to the main thread which then processes them in a ncurses environment. A basic implementation of such a queue has been added to croatoan recently. Some work has to be done to improve the code, but it works with slime nicely already.
