### ISSUE TITLE
wrong information in docstring

### ISSUE THREAD

**Issue by cage2** [McParen/croatoan#18]
Hello!

Thank you for this library, i can see this is the results of a lot of hard work!

Maybe i spotted a minor issue with the docstring of `bind` (or i missed something, not sure :-) )

``` text
If a handler for the event :default is defined, it will handle all events for which
no specific event handler has been defined.
```

I think `:default` should be `t` instead, is it?

bye!
C.

**Comment by McParen** [comment]
Hello, thanks for the hint, you are of course right. I'll push the fix with the next commit. There likely are a lot of other errors, both in the docstrings and in the code, so I'm thankful for every suggestion.

**Comment by cage2** [comment]
On Tue, Dec 17, 2019 at 01:33:06PM -0800, McParen wrote:

> Hello,

Hi!

> thanks for  the hint,

My pleasure :)

> you are of course  right. I'll push the
> fix with  the next commit.  There likely are  a lot of  other errors,
> both in  the docstrings and  in the code,  so I'm thankful  for every
> suggestion.

Thanks to you and all the  other contributors for this library, i feel
very comfortable using it. :)

Bye!
C.
