### ISSUE TITLE
Coexisting with SWANK

### ISSUE THREAD

**Issue by stacksmith** [McParen/croatoan#2]
@McParen - I've been using cl-charms, but your library seems much nicer!  

I've spent some effort trying to get swank to keep the repl going while a curses app is being worked on.  In particular, I run a swank server and connect to it from emacs... I then call a function inside the main loop that keeps REPL interactive.  During development, I often separate initialization, main loop iteration and termination; that way I can stop in the middle of the main loop - with the display active - and fix some functionality (obviously, can't always do that unless you indirect compiled calls in some places).

If you are interested I could put together a pull request.

I am also very curious about how you work with it.   Do you run a swank server?  Do you have a way of interactive development that is different from what I do?

**Comment by McParen** [comment]
Hello stacksmith,

I only briefly tried intereactive ncurses development via slime/swank, but other than making sure that it works, I did not explore it further. 

In order to keep everything as simple as possible, when testing the ncurses ui parts, I just reload from an xterm REPL.

**Comment by ahungry** [comment]
cl-charms mentions this in their readme (as well as a one-liner in how to invoke it) - given the interactive nature of CL development, I would recommend including a similar note in the readme for this project (easiest way is to start a REPL + swank in your term of choice, then slime-connect from Emacs and call whatever you want to launch the code in there).
