### ISSUE TITLE
Compile /src/util.lisp

### ISSUE THREAD

**Issue by cage2** [McParen/croatoan#21]
Hi!

I can see you are improving the library, thank you!

I have a little request: I need to use the function `key_name` and, after checking the code, i found the file `src/util.lisp` that in not in the ASDF file (please correct my if i am wrong). This file contains a little function: `key-to-string`  that i think could be useful even if it is just syntactic sugar. Moreover i can see in the same file some CFFI stuff that overlap with definitions in `ncurses/util.lisp`; are the C functions `src/util.lisp` be commented out if the latter file is included in ASDF system definition? 

If this is all is needed to export the function `key-to-string` i think i could take care of that with a pull request as these appears to be really simple changes.

Bye!
C.

**Comment by McParen** [comment]
Yes, these are some leftovers/duplicates from a time where the library was just a thin wrapper around ncurses  similar to cl-charms. I've never used the utils functions, so I never came to properly include them.

So if you want to tidy up src/utils.src, please do and thank you for that. Could you also provide a very simple example how this function can be used and tested?

**Comment by cage2** [comment]
On Sat, Dec 28, 2019 at 07:46:52AM -0800, McParen wrote:

Hi!

> Yes, these are some leftovers/duplicates from a time where the library was just a thin wrapper around ncurses  similar to cl-charms. I've never used the utils functions, so I never came to properly include them.
>
> So if you want to tidy up src/utils.src, please do and thank you for that.

Very well! i will do my best (even if i am a bit rusty with ncurses)! :)

> Could you also provide a very simple example how this function can be used and tested?

Sure,  should not  be too  difficult i  guess; i  am going  to add  an
example in the PR.

Bye!
C.
