### ISSUE TITLE
apparently unicode support was lost with sbcl 2.0.3

### ISSUE THREAD

**Issue by cage2** [McParen/croatoan#29]
Hi,

I do not know if just me but after upgraded to sbcl 2.0.3 the support for widechar seems gone and, fir unicode characters,  nothing is printed instead; to reproduce just run the test `ut01`.

Bye!
C.

**Comment by McParen** [comment]
Thanks, I have not yet tried 2.0.3, I will do that next. At the moment, I am still trying to find out what caused the unicode background routine in ncurses to stop working (issue #28).

**Comment by cage2** [comment]
On Mon, Apr 06, 2020 at 11:55:53AM -0700, McParen wrote:

Hi!

> Thanks, I  have not  yet tried 2.0.3,  I will do  that next.  At the
> moment,  I am  still  trying to  find out  what  caused the  unicode
> background routine in ncurses to stop working (issue #28).

Sure, no problem! Let's consider this issue report just as a memo.

Bye!
C.

**Comment by cage2** [comment]
On Mon, Apr 06, 2020 at 11:55:53AM -0700, McParen wrote:

Hi!

> Thanks, I  have not  yet tried 2.0.3,  I will do  that next.  At the
> moment,  I am  still  trying to  find out  what  caused the  unicode
> background routine in ncurses to stop working (issue #28).

So, i have  investigated a bit and seems that  croatoan fell victim of
the recent decision to use utf8 as default external format. :)

https://github.com/sbcl/sbcl/commit/2454a32de94b0e8e75780d72923f34fcd021820c

If  you take  a  look at  the  diff you'll  notice  that the  function
'setup_locale()' was removed aftre the changes mentioned above.

Fortunately you already provided the workaround, just define and call,
befoe `initscr', the setlocale as defined in example `ut05' of ncurses
test and wide char supports came back! :)

Of  course this  is nothing  more than  a starting  point, probably  a
better solution needs to be planned.

Hope this helps!
Bye!

**Comment by cage2** [comment]
On Tue, Apr 07, 2020 at 10:27:03AM -0700, McParen wrote:

Hi McParen!

> > just define and call, befoe `initscr', the setlocale
>
> Thanks for finding that out, this essentially solves the issue.

Good! Happy to be useful! :)

> > probably  a better solution needs to be planned.
>
> Why? The call to setlocale is the recommended way to properly start ncurses. From the man page:

[...]

> Until now,  we have  simply *relied*  on SBCL doing  this for  us by
> default, now we have to do it manually, as every other ncurses app.

Actually i thought it  was just to simple, the only thing  i did was to
check runtime.c of SBCL (as suggested  by your comment) and paste your
function into the example. Seemed just  a quick hack to me, turned out
was a good solution, instead. I find this funny someway! :D

Bye!
C.

**Comment by McParen** [comment]
I've pushed a commit adding a call to setlocale to the initialization of screen objects. For direct ncurses calls, you will have to setlocale manually every time, but that's intended.

For me this solves the issue, can it be closed?

**Comment by cage2** [comment]
On Wed, Apr 08, 2020 at 12:31:38AM -0700, McParen wrote:

Hi!

> I've pushed a commit adding a call to setlocale to the initialization of screen objects. For direct ncurses calls, you will have to setlocale manually every time, but that's intended.
>
> For me this solves the issue, can it be closed?

Wonderful, works like a charm!

Thank you!
C.
