### ISSUE TITLE
Does not build - ncurses issue

### ISSUE THREAD

**Issue by quicklisp** [McParen/croatoan#31]
I get this:

```; caught ERROR:
;   READ error during COMPILE-FILE: The symbol "SETLOCALE" is not external in the DE.ANVI.NCURSES package.
```

Full log here: http://report.quicklisp.org/2020-04-08/failure-report/croatoan.html#croatoan

**Comment by McParen** [comment]
Hello, when have you pulled from the repository?

A few hours ago, I have pushed a commit that exports the symbols. It is possible that you pulled before that commit. That was likely a very unfortunate timing.

Could you please retry?

Thanks for all the effort you invest in quicklisp.

**Comment by quicklisp** [comment]
This is working fine now, thanks.
