### ISSUE TITLE
proposing for some helpers function for complex-string

### ISSUE THREAD

**Issue by cage2** [McParen/croatoan#36]
Hi @McParen !

In all these months i wrote a few little functions that i found useful when working with `complex-string`, i believe this code could be of general use, so i wonder if i could make a PR to include this functions into the library so that other people can use them.

The original program is licensed under GPLv3 or later but, as i am the only author of the following code i can re-license with MIT for this library.

The links to said function follows:

https://notabug.org/cage/tinmop/src/master/src/tui-utils.lisp#L94

https://notabug.org/cage/tinmop/src/master/src/tui-utils.lisp#L125

https://notabug.org/cage/tinmop/src/master/src/tui-utils.lisp#L127

https://notabug.org/cage/tinmop/src/master/src/tui-utils.lisp#L194

https://notabug.org/cage/tinmop/src/master/src/tui-utils.lisp#L261

As you can see they are quite simple, so i am not even sure if there was not a way to do this kind of text manipulation using existing functions in `Croatoan`, if so just close this issue.

Looking forward to your comments!

Bye!
C.

**Comment by McParen** [comment]
Hello cage,

the utility functions certainly look useful. There are no equivalents for them in croatoan, so it would be great if you included them. Are they self-contained or would you need to include external dependencies for them? Would you mind adding docstrings? My suggestion is to put them in src/character.lisp, since that is where a recently moved the complex char/string class definitions and functions. Also a suggestion would be to rename the cat-* functions to either concat (elisp) or concatenate (cl) to better resemble existing names.

Thanks.

**Comment by cage2** [comment]
On Thu, Aug 13, 2020 at 11:34:17AM -0700, McParen wrote:
> Hello cage,

Hi!!

> the  utility   functions  certainly   look  useful.  There   are  no
> equivalents  for them  in  croatoan, so  it would  be  great if  you
> included them.

Very good! :)

> Are  they  self-contained or  would  you  need to  include  external
> dependencies for them?

Good  question! I  am  quite sure  that the  only  dependency is  just
croatoan (and  function from CL standard  of course). But of  course i
will check this and report here for any other dependency.

> Would you mind adding docstrings?

No problem, the lack of docstring is like a bug in the code for me. :)

> My suggestion  is to put  them in src/character.lisp, since  that is
> where a recently moved the complex char/string class definitions and
> functions.

I am totally agree that this is the right place for these functions.

> Also a suggestion  would be to rename the cat-*  functions to either
> concat  (elisp)  or concatenate  (cl)  to  better resemble  existing
> names.

I always  found `concatenate'  just too  long (but  this is  matter of
taste, of course ;-)), so i prefer the elisp option 'concat'.

OK  McParen,  thank  you  for considering  (and  accepting  :-))  this
proposal and  for your  suggestions!  Because  the patch  is hopefully
simple but require a bit of  works to "extract" the functions from the
main program,  i will  need some time  to prepare the  PR, but  not so
much i hope! :D

Bye!
C.

**Comment by McParen** [comment]
Hello, I've just merged the proposed additions, thanks again for your efforts.

**Comment by cage2** [comment]
On Tue, Aug 18, 2020 at 02:06:42AM -0700, McParen wrote:

> Hello,

Hello!

> I've just merged the proposed additions, thanks again for your efforts.

Thanks to you for giving me the chance to contribute to this library! :)

Bye!
C.
