### ISSUE TITLE
get_wch file functions not included in package 

### ISSUE THREAD

**Issue by emanrdesu** [McParen/croatoan#5]
sbcl 1.3.15
using croatoan from quicklisp

(defvar exsyms)
(setq exsyms (loop for x being each external-symbol in :croatoan collect x))
 > (.items set-mouse-event menu-window ....)
(length exsyms)
> 83
(member 'get-wide-char exsyms)
> nil

**Comment by McParen** [comment]
I have checked the exports in the 2017-04-03 quicklisp release, get-wide-char was exported there.

For your member-check to return non-nil, i.e. to find get-wide-char, you have to (in-package :croatoan) first, or (member 'croatoan:get-wide-char exsyms).

**Comment by emanrdesu** [comment]
(ql:uninstall :croatoan)
(ql:quickload :croatoan)
>  To load "croatoan": .....
(require :croatoan)
> nil
#'croatoan::get-char
> #<FUNCTION de.anvi.croatoan:get-char>
#'croatoan::get-wide-char
> debugger invoked on a UNDEFINED-FUNCTION in thread ...

So I went to .quicklisp to see what it had installed.
The source and ncurses folder had each 47 items, compared to the this github's clone, which had 50 for ncurses and 51 for sources.
And of course, get_wch.lisp isn't even in the quicklisps.

**Comment by emanrdesu** [comment]
Yeah, user error.
I thought quicklisp updated automatically.
