### ISSUE TITLE
#\horizontal_ellipsis is not recognized by some implementations

### ISSUE THREAD

**Issue by Yehouda** [McParen/croatoan#53]
https://github.com/McParen/croatoan/blob/8a36ee126ee6be41dd9ab65a0b8a1b5a0080c6a3/src/menu.lisp#L111

#\horizontal_ellipsis  is not a standard character is common-lisp, so will not be recognize by some implementations and wil get an error. 

replacing it by `(code-char #x2026)` make it poratble for all implementations.  

Maybe make clearer to read by defining
```
(defconstant *horizontal-ellipsis-char* (code-char #x2026))
```
and then use **\*horizontal-ellipsis-char***.

**Comment by McParen** [comment]
Hello Yehouda,

although I am not able to perform tests on all implementations for time constraint reasons, I will gladly accept suggestions to make the library run on as many implementations as possible. So thank you very much for your contribution, I will include it with the next patch. You are welcome suggesting further changes and making your implementation run the code well.

Kind regards.

**Comment by McParen** [comment]
I think I have solved your issue with the above patch, thanks for testing the library with LW and reporting.
