### ISSUE TITLE
Compilation issue with last commit

### ISSUE THREAD

**Issue by cage2** [McParen/croatoan#54]
Hi @McParen !

Seems that there is some spurious code in croatoan.lisp here:

https://github.com/McParen/croatoan/blob/master/src/croatoan.lisp#L221

That prevents compilation, i commented the last form that starts with `((listp...` and everything to appears to work fine, then. But i am not sure if i did it well! :smile: 

Anyway let me wish you: seasons greetings!

C.

**Comment by McParen** [comment]
Hello cage, thanks a lot for the report. I did not notice such an issue during my test runs, but I will take a more detailed look. Have a nice few remaining days of the year.

McP

**Comment by McParen** [comment]
Hello cage, I've now removed that piece of dead code, which actually was supposed to be replaced in that commit. I can not really explain how that ended up in the commit, since it is not present in my working copy. When in doubt, it's emacs' fault. ;) Have a few more greetings and thanks. McP.

**Comment by cage2** [comment]
On Tue, Dec 26, 2023 at 11:03:44AM -0800, McParen wrote:

Thank you very much McParen! 🎄

Bye!
C.
