### ISSUE TITLE
Why is MFA enforcement a problem?!?

### ISSUE THREAD

**Issue by Hexstream** [McParen/croatoan#55]
Hello,

The README says this:

> Due to threats of enforcement of two-factor authentication by Microsoft, this repository has been migrated to Codeberg, a non-profit Git hosting platform for Free Software

Pardon my ignorance, I completely fail to understand why MFA enforcement is any sort of reason to move away from GitHub?!?

**Comment by McParen** [comment]
Hello, I do not know about you, but I do not enjoy being threatened by american for-profit companies during my leisure time. 

_"We need you to do X by date Y, or we will do Z to you. Here's how to comply quickly."_

When I joined Github before the corporate takeover it was for fun and learning on an free, independent platform, not being bullied by the notorious new owner because my worldview doesn't align with their board's strategic vision how to "move forward". They can do that to their employees or their fanboys, but I am neither of them.

**Comment by Hexstream** [comment]
"_Threatened_" seems to imply _potential future harm_, whereas in fact
**enforcing MFA obviously greatly reduces overall harm globally...**

I really don't think it's safe at all to assume that GitHub wouldn't have enforced MFA along a similar timeline if Microsoft had never acquired them. Frankly, I must say I have been _surprisingly pleased_ with the acquisition, with virtually no drawbacks I am aware of.

I just don't get the unending panic thing, especially when it leads to tons of _completely gratuitous and unwarranted_ **project "suicides"** through hosting on random other code hosting platforms. **_That just completely kills usability for almost all users..._** Ah well!

I suggest simply enrolling in [Google's Advanced Protection program](https://landing.google.com/advancedprotection/), and then you'll have everything you need to trivially implement MFA on GitHub and anywhere else that supports security keys.

**Comment by McParen** [comment]
> enforcing MFA obviously greatly reduces overall harm globally.

I do not enjoy "taking one for the team". If you do, have fun.

> I have been surprisingly pleased

Oh, you already do. Nevermind.

> just completely kills usability for almost all users...

Attempting to leave Microsoft's plantation you've been involuntarily trapped into.... just completely kills usability for almost all users.

> "suicides" through hosting on ... other ... platforms

Orwellian word-twisting straight out of the depths of coke-ridden corporate PR departments. Spooky. I thougt you guys existed only in dystopian satires.

> "Here's how to comply quickly."

- simply enrolling
- you'll have everything you need
- trivially implement

Are you sure you're not a bot? Spooky.
