### ISSUE TITLE
(add-string win str) doesn't work when (type-of str) == 'complex-string

### ISSUE THREAD

**Issue by emanrdesu** [McParen/croatoan#6]
Reason being you can't #'length a complex-string, which is what happens in the let form inside #'add-string.

**Comment by McParen** [comment]
Hello,

thanks for your report. I am aware of this difficulty. I thought about making complex-string a user defineable sequence, but that only works for SBCL.

I've added a typecase to add-string, and I think a lot of typecases will be necessary all over the place, and I am not happy with that. I'd like to have a cleaner way to deal with user-defined string types.

**Comment by emanrdesu** [comment]
Did you add the temporary fix to the quicklisp's?
