### ISSUE TITLE
Don't know where else to ask, but is it possible for you to make .complex-char-array be exported?

### ISSUE THREAD

**Issue by emanrdesu** [McParen/croatoan#7]
I don't want to be annoying, but please do.

**Comment by McParen** [comment]
Thanks for your feedback, it is not annoying. If you have a suggestion how to improve the complex-string interface, please contribute.

As I mentionend in another issue, I'd like to turn complex-string into a user defineable sequence class, but this extension is only supported by sbcl, which is unfortunate.
